---
- name: Initialize Raspberry Pis
  hosts: all
  remote_user: pi
  become: true
  become_user: root

  roles:
    - {role: raspbian_init}
    - {role: sysupdate}

- name: Provision Master Node
  hosts: master
  remote_user: pi
  become: true
  become_user: root

  roles:
    - {role: k3s_master}

- name: Provision Worker Nodes
  hosts: nodes
  remote_user: pi
  become: true
  become_user: root

  roles:
    - {role: k3s_node}
