---
# yamllint disable rule:line-length
- hosts: master:nodes
  gather_facts: false
  tasks:
    - name: Shutdown
      command: shutdown -h now
      changed_when: false
      become: true

    - name: Save target host IP
      set_fact:
        target_host: "{{ ansible_host }}"

    - name: Wait for host
      wait_for: "port=22 host={{ target_host }} delay=10 state=stopped timeout=60"
      delegate_to: 127.0.0.1
